### ISSUE TITLE
IndexError: deque index out of range

### ISSUE THREAD

**Issue by li-rukun** [MarkFzp/navigation-locomotion#1]
Hi, I got an error when running main.py:
`-----sleep for 2s, building up perception buffer-----

--------------------------
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    main()
  File "main.py", line 193, in main
    mmap, pos_mm, yaw, target_pos_mm = slam.get_global_map(target_pos)
  File "main.py", line 120, in get_global_map
    map, _ = self.get_map()
  File "main.py", line 44, in get_map
    data = self.map_buffer[-1]
IndexError: deque index out of range`
What's the reason?How can I modify it?

**Comment by MarkFzp** [comment]
I think your occupancy ros node has not been launched or not properly launched. 
`roslaunch occupancy occupancy_live_rviz.launch`
