### ISSUE TITLE
Two questions about the project

### ISSUE THREAD

**Issue by Hourse-xing** [MarkFzp/navigation-locomotion#2]
Dear author, I have two questions for you.
        First, I would like to ask what computing platform is used in this project. Can you tell me in detail? Is it Jetson Xavier NX?
        Second, I want to ask whether there is no reinforcement learning code in this project. For example, the obstacle_detector.py and terrain_detector.py in the plan_cts_pid file only have interfaces to receive whether obstacles are encountered or whether speed should be limited. But there is no code in the plan_cts_pid file to judge the motion state of the robot in the previous step.

**Comment by MarkFzp** [comment]
Thanks for your interests!
1. We ran the algorithm on a Jetson NX of the A1
2. right now we didn't have a nice way to release robot policy since it depends on many onboard c++ codes and sdks. will let you know when it's released

**Comment by xuyuxiu83** [comment]
> Thanks for your interests!
> 
> 1. We ran the algorithm on a Jetson NX of the A1
> 2. right now we didn't have a nice way to release robot policy since it depends on many onboard c++ codes and sdks. will let you know when it's released

Hi! I'd like to inquire whether you still plan to open-source the training code? Or are there any similar projects you could recommend as a reference for my future work? Any suggestions you may have are greatly appreciated.
